---
- name: Network Operation - Update Hostname with NetBox Verification
  hosts: Router1
  gather_facts: no
  connection: network_cli 
  vars:
    ansible_network_os: cisco.ios.ios
    netbox_url: "http://10.201.6.37:8000"
    netbox_token: "nbt_HaQ2sxFncXGG.kH2ecpVv5zIwCGL2rekELmnGTUJLGMXl5WhNQoB2"

  tasks:
    - name: 1. Fetch Device Details from NetBox
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/dcim/devices/?name={{ inventory_hostname | urlencode }}"
        method: GET
        status_code: 200
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
      register: device_query
      delegate_to: localhost

    - name: 2. Fail if device is not in NetBox
      ansible.builtin.fail:
        msg: "Device {{ inventory_hostname }} not found in NetBox. Aborting."
      when: device_query.json.count == 0

    - name: 3. Change Hostname on Router
      cisco.ios.ios_hostname:
        config:
          hostname Testing123
        state: merged
      when: target_hostname is defined and target_hostname | length > 0

    - name: 4. Verify Change
      cisco.ios.ios_command:
        commands:
          - show running-config | include hostname
      register: verify_output

    - name: 5. Display Result
      ansible.builtin.debug:
        msg: "Hostname updated successfully. Router reports: {{ verify_output.stdout[0] }}"
