- name: Network Operation - Update Hostname
  hosts: Router1
  gather_facts: no

  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Configure Hostname to Router1-AWX
      cisco.ios.ios_hostname:
        config:
          hostname: Router1-AWX
        state: merged
