---
- name: Device Info Report - Hostname, User, and SSH
  hosts: Router1
  gather_facts: no

  tasks:
    - name: 1. Gather Raw Data from Router
      cisco.ios.ios_command:
        commands:
          - show running-config | include hostname
          - show users
          - show ip ssh | include SSH
      register: device_output

    - name: 2. Process and Clean Data
      ansible.builtin.set_fact:
        clean_hostname: "{{ device_output.stdout[0].split(' ')[1] | default('N/A') }}"
        clean_users: "{{ device_output.stdout[1].splitlines() }}"
        clean_ssh: "{{ device_output.stdout[2].splitlines() }}"

    - name: 3. Display High-Fidelity Dashboard
      ansible.builtin.debug:
        msg: |
          ╔══════════════════════════════════════════════════════════════╗
          ║                 NETOPS DEVICE INSIGHT REPORT                 ║
          ╠══════════════════════════════════════════════════════════════╣
            DEVICE IDENTITY
            » Hostname     : {{ clean_hostname }}
            » Status       : ONLINE (Reachable via AWX)
            » Connection   : network_cli (Cisco IOS)
            » Target IP    : {{ ansible_host }}
            » Source       : NetBox Verified
          ----------------------------------------------------------------
            SECURITY & ACCESS
            » SSH Protocol : {{ clean_ssh[0] | trim }}
            » Admin Session: {{ ansible_user | upper if ansible_user is defined else 'ADMIN' }}
          ----------------------------------------------------------------
            CURRENTLY ACTIVE SESSIONS
          {% for line in clean_users %}
            • {{ line }}
          {% endfor %}
          ╚══════════════════════════════════════════════════════════════╝
