---
- name: Device Info Report - Hostname, User, and SSH
  hosts: Router1
  gather_facts: no

  tasks:
    - name: 1. Gather Raw Data from Router
      cisco.ios.ios_command:
        commands:
          - show running-config | include hostname
          - show users
          - show ip ssh | include SSH
      register: device_output

    - name: 2. Process and Clean Data
      ansible.builtin.set_fact:
        clean_hostname: "{{ device_output.stdout[0].split(' ')[1] | default('N/A') }}"
        # We combine everything into one list of strings for a clean vertical scroll
        report_lines:
          - "╔══════════════════════════════════════════════════════════════╗"
          - "║                 NETOPS DEVICE INSIGHT REPORT                 ║"
          - "╠══════════════════════════════════════════════════════════════╣"
          - "  DEVICE IDENTITY"
          - "  » Hostname     : {{ device_output.stdout[0].split(' ')[1] | default('N/A') }}"
          - "  » Status       : ONLINE (Reachable via AWX)"
          - "  » Target IP    : {{ ansible_host }}"
          - "----------------------------------------------------------------"
          - "  SECURITY & ACCESS"
          - "  » SSH Protocol : {{ device_output.stdout[2] | trim }}"
          - "----------------------------------------------------------------"
          - "  CURRENTLY ACTIVE SESSIONS"
