---
plugin: netbox.netbox.nb_inventory
api_endpoint: "http://10.201.6.37:8000"
token: "nbt_JQsOeqlRuRXm.nfKEnanb1dM2QySlMfDwX17r8X6ojGooCrO3EWZk"
validate_certs: false
group_by:
  - device_roles
  - sites
